### ISSUE TITLE
test example

### ISSUE THREAD

**Issue by wangjiawen2013** [DavisWeaver/crosstalkr#7]
Hi,
This work is very useful to me. Could you provide some detailed tutorials and datasets and examples ?

**Comment by DavisWeaver** [comment]
Have you taken a look at the paper? https://www.biorxiv.org/content/10.1101/2023.03.07.531526v1 - there is more detail in there. If you have specific questions about functionality that isn't covered either there or in the readme feel free to let me know and I can try to add some more documentation!

**Comment by DavisWeaver** [comment]
gonna close this for now
